---
kind: pipeline
name: default

trigger:
  event:
    - push
  branch:
    - main
steps:
  - name: Create and upload Docker Image
    image: plugins/docker
    settings:
      registry: registry.der-taenzer.net
      username:
        from_secret: REGISTRY_USER
      password:
        from_secret: REGISTRY_PASS
      repo: registry.der-taenzer.net/tnz/eventverein-stadt-kalender
      tags:
        - latest
        - build-${DRONE_BUILD_NUMBER}
      dockerfile: ./Dockerfile
      context: .
  - name: Refresh Docker Stack
    image: plugins/webhook
    settings:
      urls: https://docker.der-taenzer.net/api/stacks/webhooks/c989f771-0f90-4f98-a1a8-c5878b482330?BUILD_NR=${DRONE_BUILD_NUMBER}&BUILD_DATE=${DRONE_BUILD_CREATED}
